#!/bin/bash
# Start varnish and log
# Starting Varnish
echo -e "\nStarting Varnish\n"
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}
echo -e "\nVarnish Started\n"
# Wait for varnish to start
sleep 15
# Showing Varnish Logs
echo -e "\nOpen Logs\n"
varnishlog